name: Create Summaries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python summary.py
          ls
      - name: Commit report
        run: |
          git config --global user.name 'MatejMecka'
          git config --global user.email 'matejmecka@users.noreply.github.com'
          git commit -am "Automated report"
          git push
